version: "3.4"

services:
  app:
    build: ./
    container_name: app
    restart: always
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    command: "npm run start"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
