name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Check pnpm version
        run: pnpm --version
      - name: pnpm i
        run: pnpm i
      - name: Get current date
        id: date
        run: echo "VERSION=date::$(date +'%y%m%d.%H%M')" >> $GITHUB_OUTPUT
      - name: pnpm run generate
        run: VERSION="${{ env.action_state }}" pnpm run generate
      - name: copy file via scp
        uses: appleboy/scp-action@master
        with:
          host: 195.201.16.124
          username: root
          key: ${{ secrets.SSH2 }}
          port: 22
          source: "dist"
          target: "/var/www/dnbradio_site/html/player"
