name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - staging
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"
      - name: Install pnpm
        run: npm install -g pnpm && node --version
      - name: Check pnpm version
        run: pnpm --version
      - name: pnpm i
        run: pnpm i
      - name: pnpm run generate-prod
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/staging'
        run: |
          pnpm run generate-prod
          mv dist player

      - name: scp -> forge:prod:dnbradio.com/player
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@master
        with:
          host: 78.47.85.152
          username: forge
          key: ${{ secrets.SSH2 }}
          port: 22
          source: "./player/*"
          target: "/home/forge/dnbradio.com/public/"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 78.47.85.152 >> ~/.ssh/known_hosts

      - name: scp -> staging.dnbradio.com/player
        if: github.ref == 'refs/heads/staging'
        uses: fifsky/ssh-action@master
        with:
          host: 78.47.85.152
          user: forge
          key: ${{ secrets.SSH2 }}
          port: 22
          command: |
            cd /home/forge/staging.dnbradio.com/public/
            scp -r ../../player/* .