name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version: "16.19.1"
      - name: Install pnpm
        run: npm install -g pnpm && node --version
      - name: Check pnpm version
        run: pnpm --version
      - name: pnpm i
        run: pnpm i
      - name: pnpm run generate-prod
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
        run: |
          pnpm run generate-prod
          mv dist player
      - name: scp -> dnbradio.com/player
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@master
        with:
          host: 3.238.78.182
          username: forge
          key: ${{ secrets.SSH2 }}
          port: 22
          source: "./player/*"
          target: "/hoome/forge/dnbradio.com/public/"
      - name: scp -> dnbradio.com/player-dev
        if: github.ref == 'refs/heads/dev'
        uses: appleboy/scp-action@master
        with:
          host: 44.193.210.138
          username: forge
          key: ${{ secrets.SSH2 }}
          port: 22
          source: "./player/*"
          target: "/home/forge/staging.dnbradio.com/public/"
