name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version: "16.19.1"
      - name: Install pnpm
        run: npm install -g pnpm && node --version
      - name: Check pnpm version
        run: pnpm --version
      - name: pnpm i
        run: pnpm i
      - name: pnpm run generate-prod
        if: github.ref == 'refs/heads/main'
        run: |
          pnpm run generate-prod
          mv dist player
      - name: scp -> dnbradio.com/player
        if: github.ref == 'refs/heads/main'
        uses: appleboy/scp-action@master
        with:
          host: trace.dnbradio.com
          username: root
          key: ${{ secrets.SSH2 }}
          port: 22
          source: "./player/*"
          target: "/root/apps/www/html/"
      - name: pnpm run generate
        if: github.ref == 'refs/heads/dev'
        run: |
          pnpm run generate
          mv dist player-dev
      - name: scp -> dnbradio.com/player-dev
        if: github.ref == 'refs/heads/dev'
        uses: appleboy/scp-action@master
        with:
          host: trace.dnbradio.com
          username: root
          key: ${{ secrets.SSH2 }}
          port: 22
          source: "./player-dev/*"
          target: "/root/apps/www/html/"
