name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "16.19.1"
      - name: Install pnpm
        run: npm install -g pnpm && node --version
      - name: Check pnpm version
        run: pnpm --version
      - name: pnpm i
        run: pnpm i
      - name: pnpm run prod-generate
        run: |
          pnpm run prod-generate
          mv dist player
      - name: scp -> dnbradio.com/player
        uses: appleboy/scp-action@master
        with:
          host: 195.201.16.124
          username: root
          key: ${{ secrets.SSH2 }}
          port: 22
          source: "./player/*"
          target: "/tmp/var/www/dnbradio_site/html/"
